# Generated by Django 3.2.5 on 2021-12-01 21:17

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/projects', validators=[projects.models.file_size]),
        ),
    ]
