# Generated by Django 3.2.5 on 2021-08-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210818_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_lin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
