# Generated by Django 3.2.5 on 2021-08-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_social_lin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_red',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=800),
        ),
    ]
