# Generated by Django 3.2.5 on 2021-08-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210820_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_red',
        ),
    ]
