# Generated by Django 3.2.5 on 2021-08-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_fb',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_git',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_insta',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_lin',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_tw',
            new_name='twitter_url',
        ),
    ]
